### PR TITLE
Fix registration events duplication on update

### LINKED ISSUE #957: Psych sheet bug
Just a small bug I noticed on the Skillcon 2016 psych sheet:

https://www.worldcubeassociation.org/competitions/Skillcon2016/registrations/psych-sheet/333

Tristan Doan is listed twice for all events that he is registered for.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #957.

I think about an appropriate migration now, that will clean the duplications.

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Ok, I've added the migration.

File: WcaOnRails/app/models/registration.rb [hunk 1]
```diff
@@ -140,7 +140,7 @@ def waiting_list_info
   def events_to_associated_events(events)
     events.map do |event|
       competition_event = competition.competition_events.find_by!(event: event)
-      registration_competition_events.find_by_competition_event_id(event.id) || registration_competition_events.build(competition_event: competition_event)
+      registration_competition_events.find_by_competition_event_id(competition_event.id) || registration_competition_events.build(competition_event: competition_event)
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/registration.rb]: Just to clarify: this mistaken variable name caused the *find* to fail (return `nil`) so that we built a new object.

**Comment by larspetrus** [comment]
Can we put a uniqueness constraint on this?

File: WcaOnRails/app/models/registration.rb (hunk 1 above)
Comment (jfly) [inline WcaOnRails/app/models/registration.rb]: Urg... sorry about that.

**Comment by jfly** [comment]
I agree with @larspetrus, it would be nice to make sure we cannot do this to ourselves again.

**Comment by jonatanklosko** [comment]
Done. I had to specify the index name myself because the migration failed saying the name was too long.

**Comment by jfly** [comment]
LGTM!
