### PR TITLE
Check if rows are empty before calculating by-region rankings

### LINKED ISSUE #6325: Certain combinations of filter criteria break the rankings page
**Describe the bug**
When combining particular filter critera, the ranking page yields the "We're sorry, but something went wrong" error page

**To Reproduce**
Steps to reproduce the behavior [EXAMPLE, breaks for several other conditions as well]:
1. Go to "Rankings"
2. Choose the Megaminx event
3. Filter for Female competitors
4. Filter for Averages
5. Filter "By region"
6. Filter for years until 2006
7. KABOOM

**Expected behavior**
An empty rankings page is being displayed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux 5.10.42
 - Browser: Chrome
 - Version: 91.0.4472.77

**Smartphone (please complete the following information):**
 N/A

**Additional context**
Presumably the SQL query yields a non-trivial result set. According to the staging logs, there is a `Nil` result involved somewhere.

```
I, [2021-06-25T22:43:37.961849 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] Started GET "/results/rankings/minx/average?gender=Female&show=by+region&years=until+2006" for 79.207.189.56 at 2021-06-25 22:43:37 +0000
I, [2021-06-25T22:43:37.963404 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] Processing by ResultsController#rankings as HTML
I, [2021-06-25T22:43:37.963461 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Parameters: {"gender"=>"Female", "show"=>"by region", "years"=>"until 2006", "event_id"=>"minx", "type"=>"average"}
D, [2021-06-25T22:43:37.972269 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]    (6.5ms)  SELECT `Competitions`.`year` FROM `Competitions` WHERE `Competitions`.`showAtAll` = TRUE
I, [2021-06-25T22:43:37.982184 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendering results/rankings.html.erb within layouts/application
D, [2021-06-25T22:43:37.984508 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Event Load (1.3ms)  SELECT `Events`.* FROM `Events` WHERE (`rank` < 990) ORDER BY `Events`.`rank` ASC
I, [2021-06-25T22:43:38.010826 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendered results/_results_selector.html.erb (28.2ms)
D, [2021-06-25T22:43:38.012743 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Timestamp Load (1.2ms)  SELECT  `timestamps`.* FROM `timestamps` WHERE `timestamps`.`name` = 'compute_auxiliary_data_end' LIMIT 1
D, [2021-06-25T22:43:38.418850 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   SQL (405.4ms)          SELECT
          result.*,
          result.average value
        FROM (
          SELECT
            result.countryId recordCountryId,
            MIN(average) recordValue
          FROM ConciseAverageResults result
          JOIN Persons persons ON result.personId = persons.id and persons.subId = 1
          WHERE 1
            AND eventId = 'minx'
            AND result.year <= 2006
            AND gender = 'f'
          GROUP BY result.countryId
        ) record
        JOIN Results result ON result.average = recordValue AND result.countryId = recordCountryId
        JOIN Competitions competition on competition.id = competitionId
        JOIN Persons persons ON result.personId = persons.id and persons.subId = 1
        WHERE 1
          AND eventId = 'minx'
          AND competition.year <= 2006
          AND gender = 'f'
        ORDER BY value, countryId, start_date, personName

D, [2021-06-25T22:43:38.420830 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Competition Load (1.3ms)  SELECT `Competitions`.* FROM `Competitions` WHERE 1=0
I, [2021-06-25T22:43:38.422201 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendered results/_rankings_by_region_table.html.erb (1.1ms)
I, [2021-06-25T22:43:38.422367 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendered results/rankings.html.erb within layouts/application (440.1ms)
I, [2021-06-25T22:43:38.422611 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] Completed 500 Internal Server Error in 459ms (ActiveRecord: 415.6ms)
I, [2021-06-25T22:43:38.422883 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] [User Id] Request was made by user id: <not logged in>
F, [2021-06-25T22:43:38.424251 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]
F, [2021-06-25T22:43:38.424293 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
F, [2021-06-25T22:43:38.424467 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]     1: <% rows_to_display, first_continent_index, first_country_index = compute_rankings_by_region(@rows, @continent, @country) %>
[a7117224-b0b1-4c27-8d1c-629a581e2304]     2: <%= wca_table table_class: "wca-results" do %>
[a7117224-b0b1-4c27-8d1c-629a581e2304]     3:   <thead>
[a7117224-b0b1-4c27-8d1c-629a581e2304]     4:     <tr>
F, [2021-06-25T22:43:38.424497 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]
F, [2021-06-25T22:43:38.424518 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] app/helpers/results_helper.rb:33:in `compute_rankings_by_region'
[a7117224-b0b1-4c27-8d1c-629a581e2304] app/views/results/_rankings_by_region_table.html.erb:1:in `_app_views_results__rankings_by_region_table_html_erb__4034573802227995242_105792100'
[a7117224-b0b1-4c27-8d1c-629a581e2304] app/views/results/rankings.html.erb:22:in `block in _app_views_results_rankings_html_erb___2926773708043788757_70101186865260'
[a7117224-b0b1-4c27-8d1c-629a581e2304] app/views/results/rankings.html.erb:11:in `_app_views_results_rankings_html_erb___2926773708043788757_70101186865260'
[a7117224-b0b1-4c27-8d1c-629a581e2304] lib/middlewares/warden_user_logger.rb:13:in `call'
[a7117224-b0b1-4c27-8d1c-629a581e2304] lib/middlewares/fix_accept_header.rb:14:in `call'
```

### PR DESCRIPTION
**Pull request by louismeunier**
To fix #6325

### CODE REVIEW

**Review by gregorbg — CHANGES_REQUESTED** [review]
Great, you spotted the error! Your approach works but I'd rather not fix the error by deliberately assigning an explicit null value. (Note that this is only a design/code style concern)

I suggest one of the two following approaches:
1. Assume that the return value of `rows.first` can be nil and execute the getter via the nil-safe `&.` operator (most other languages use `?.` notation) like so: `rows.first&.do_something()`
2. At the very top of the method, add a special check for when `rows` is empty, and directly return without doing any computations
```
if rows.empty?
    return reasonable_default
end
```

I'm open to either approach, try whatever you think works/looks best. You have to figure out what to insert instead of `do_something` and `reasonable_default` respectively; I'll leave that as an exercise but I have solutions for both cases so you can ask me if you need help :)

Other WST members can also express their preferences for either of the two suggested alternatives, perhaps use the emoji button to react with a `1` or `2` symbol Emoji if you have strong preferences.

**Comment by louismeunier** [comment]
Alright, thanks for the input! For 1), your assumption of the first value potentially being `nil` is correct, which was what was causing the issue in the first place (the original method was simply calling `["value"]` on that value, which obviously broke whenever it was `nil`. As such, both of your solutions work. I originally had something similar to 2) written out, but I'm pretty indifferent to one method over another, so I'll wait for some other input.

**Comment by jonatanklosko** [comment]
Generally speaking, approach 2. is a bit more clear, because eliminating edge cases makes it easier to write and reason about the subsequent code. Once we are familiar with the code, either approach makes just as much sense, but when reading for the first time (or after a while ^^), I think 2. is most helpful. In this specific case I don't have a strong opinion and would be fine with either of the three versions though.

File: WcaOnRails/app/helpers/results_helper.rb [hunk 1]
```diff
@@ -30,6 +30,9 @@ def historical_pb_markers(results)
   end
 
   def compute_rankings_by_region(rows, continent, country)
+    if rows.empty?
+      return [[]]
```
Comment (gregorbg) [inline WcaOnRails/app/helpers/results_helper.rb:34]: Why are you returning a list within a list here? The original return statement below reads 
```
[rows_to_display, first_continent_index, first_country_index]
```
which is a triple of a list and two ints. You should also return a list and two ints here in my opinion.

**Review by gregorbg — CHANGES_REQUESTED** [review]
Thanks, you got the overall change quite right!
Just one nitpick about the structure of the return value and then we're good to go!

File: WcaOnRails/app/helpers/results_helper.rb (hunk 1 above)
Comment (louismeunier) [reply WcaOnRails/app/helpers/results_helper.rb:34]: I see what you mean, but I'm not sure what two ints would make the most sense here, as they simply indicate where in the array the data for continent & country results start. Since there is no such data, perhaps -1?

Comment (gregorbg) [reply WcaOnRails/app/helpers/results_helper.rb:34]: `0, 0` will do. Pretend that the code didn't crash at the `first` invocation, then the other variables would contain an empty list and the `for` loop would effectively not be a loop, leaving the variables at `0`.

Furthermore, I think returning `-1` is not a good idea because it can lead to "IndexOutOfBound" crashes down the line.

**Review by gregorbg — APPROVED** [review]
LGTM! :smile:
