### PR TITLE
ILR Frontend table Column Count fixes

### LINKED ISSUE #14002: Results-by-person page always show 5 attempts
Image

### PR DESCRIPTION
**Pull request by FinnIckler**
fixes #14002 and #13789

### CODE REVIEW

File: next-frontend/src/app/(wca)/competitions/[competitionId]/live/competitors/[registrationId]/page.tsx [hunk 1]
```diff
@@ -39,7 +40,9 @@ export default async function PersonResults({
           <ByPersonByRoundTable
             eventResults={eventResults}
             competitionId={competitionId}
-            rounds={rounds}
+            rounds={rounds.filter(
+              (r) => parseActivityCode(r.id).eventId == key,
+            )}
```
Comment (gregorbg) [inline next-frontend/src/app/(wca)/competitions/[competitionId]/live/competitors/[registrationId]/page.tsx]: This should not happen inside a component constructor. The only time when you every really "compute" something inline in props is for (a) boolean comparisons or (b) short callbacks like `{() => doSomething()}` one-liners.

**Review by gregorbg — CHANGES_REQUESTED** [review]

**Review by gregorbg — APPROVED** [review]
