### PR TITLE
Fix emails locales

### LINKED ISSUE #4687: "You've been added as an organizer" email sent out in wrong language
These emails get sent out in the language that the person who created the competition page has their WCA account set to, rather than the language the email recipients have their accounts set to.

Here's an example. The email got sent out to all the organizers in Italian, which is the language I have my WCA account set to. 

Screenshot 2019-10-05 21 24 02

### PR DESCRIPTION
**Pull request by tussosedan**
Fixes #4687

### CODE REVIEW

File: WcaOnRails/app/mailers/competitions_mailer.rb [hunk 1]
```diff
@@ -20,28 +20,28 @@ def notify_wcat_of_confirmed_competition(confirmer, competition)
     end
   end
 
-  def notify_organizers_of_confirmed_competition(confirmer, competition)
+  def notify_organizer_of_confirmed_competition(confirmer, competition, organizer)
```
Comment (viroulep) [inline WcaOnRails/app/mailers/competitions_mailer.rb]: What about keeping the same function name/arguments and simply doing the loop over organizers in that function?
We even have a check for `organizers.empty?` whereas it could now safely be replaced by a `@competition.organizers.each ...` :)

Comment (tussosedan) [reply WcaOnRails/app/mailers/competitions_mailer.rb]: I wanted to align it with the existing notify_organizer methods, for which the controller is the one doing the looping, instead of having two looping in the controller and two looping in the mailer. How does that sound?
Actually forgot to remove the `empty?` check though, I think it's not needed now.

Comment (viroulep) [reply WcaOnRails/app/mailers/competitions_mailer.rb]: Ah I did not notice we were looping in the controller for others too, then it seems fine :)
(I personally think it makes sense to delegate to the mailer how to handle mailing "organizers", but looping in the controller definitely makes sense)

The `empty?` check looks useless indeed :)

Comment (tussosedan) [reply WcaOnRails/app/mailers/competitions_mailer.rb]: Right, should be all done now.

Comment (tussosedan) [reply WcaOnRails/app/mailers/competitions_mailer.rb]: Right, should be all done now.
