### PR TITLE
Decide between competition.year or result.year by query param

### LINKED ISSUE #5920: Can't show top X results filtered by year
**Describe the bug**
Reported by Timo Norrkniivilä in Slack

> In the rankings, showing "x results" or results "by region" from "only year x" or "until year x", crashes.
For example https://www.worldcubeassociation.org/results/rankings/333/single?region=world&show=100+results&years=only+2020

**To Reproduce**
1. Go to 'https://www.worldcubeassociation.org/results/rankings/333/single'
2. In Years, select "Only X" or "Until X"
3. In Show, select "100 Results"

**Expected behavior**
Show top X results in a specific year

**Additional context**
Add any other context (for instance the language you're using the site in) about the problem here.

### PR DESCRIPTION
**Pull request by campos20**
Fixes #5920

### CODE REVIEW

File: WcaOnRails/app/controllers/results_controller.rb [hunk 1]
```diff
@@ -285,9 +285,9 @@ def records
     @is_until = splitted_years_param[0] == "until"
     @year = splitted_years_param[1].to_i
     if @is_only
-      @years_condition = "AND result.year = #{@year}"
+      @years_condition = @is_results ? "AND result.year = #{@year}" : "AND competition.year = #{@year}"
     elsif @is_until
-      @years_condition = "AND result.year <= #{@year}"
+      @years_condition = @is_results ? "AND result.year <= #{@year}" : "AND competition.year <= #{@year}"
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/results_controller.rb:290]: This is a bit tricky, I believe it should actually be the other way round. If `@is_results` is set it means we select from the `Results` table which has no year, so we can use the competition year instead. In other case `result` is just an alias for `Concise*Results` table which does in fact include the year ^^

Comment (campos20) [reply WcaOnRails/app/controllers/results_controller.rb]: It turns out that was not the issue

**Comment by campos20** [comment]
We could use some coverage here https://coveralls.io/builds/35491243/source?filename=app%2Fcontrollers%2Fresults_controller.rb#L286

File: WcaOnRails/app/controllers/results_controller.rb [hunk 2]
```diff
@@ -281,8 +281,8 @@ def records
 
     @is_all_years = params[:years] == "all years"
     splitted_years_param = params[:years].split
-    @is_only = splitted_years_param[0] == "only"
-    @is_until = splitted_years_param[0] == "until"
+    @is_only = splitted_years_param[1] == "only"
+    @is_until = splitted_years_param[1] == "until"
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/results_controller.rb:285]: `params[:years]` comes as `"until 2020"`, so `splitted_years_param` is `["until", "2020"]`, thus the current logic is perfectly fine. I actually think the first change you pushed was the right solution (except it should be the other way round as I mentioned) :>

Comment (campos20) [reply WcaOnRails/app/controllers/results_controller.rb:285]: Please fetch my branch and try it locally. I believe it's correct as is

Comment (jonatanklosko) [reply WcaOnRails/app/controllers/results_controller.rb:285]: It certainly doesn't produce an error, but doesn't work either. It basically makes `@is_only` and `@is_until` always false, because their are the result of `"2020" == "only"` and `"2020" == "until"` respectively. If you look one line below you can see that we actually parse `splitted_years_param[1]` as a year.

Looking more on the queries I see the year condition is mostly used where we query the results table, so it doesn't work most of the time (which is the case if you use only/until with results/region or on the records page). I'm surprised this hasn't been noticed sooner actually. Some queries even use the condition in two ways, if you look at [this one](https://github.com/thewca/worldcubeassociation.org/blob/d153d6eb6a765395a176bea4c92329704982a223/WcaOnRails/app/controllers/results_controller.rb#L106-L129), `@years_condition` is first used on the `Concise*Results.year`, but in the outer query it should refer to `Competitions.year`.

All of these queries need to be cleaned up eventually, but I think it's gonna be hard until we can make migrations on the old tables more freely and restructure the db. For now I think the easiest way would be to set the year condition right before each query, so that it uses the right table. I'm sorry you run into this messy part of the codebase, it's been ported quite directly from the PHP version and the query generation is still quite dirty. If you want to try fixing all the year conditions then feel free to do so, otherwise let me know and I can have a closer look on fixing that.

**Review by jonatanklosko — APPROVED** [review]
Great fix, thanks!
