### PR TITLE
Don't crash on startup if wca-regulations.json is missing.

### LINKED ISSUE #1063: Spinning up a new server dies due to missing wca-regulations.json
In the screen session:

```
I, [2016-12-31T18:54:47.677151 #26131]  INFO -- : Writing /home/cubing/worldcubeassociation.org/WcaOnRails
/public/assets/font-awesome/fontawesome-webfont-a7c7e4930090e038a280fd61d88f0dc03dad4aeaedbd8c9be3dd9aa4c3
b6f8d1.woff
I, [2016-12-31T18:54:47.677629 #26131]  INFO -- : Writing /home/cubing/worldcubeassociation.org/WcaOnRails
/public/assets/font-awesome/fontawesome-webfont-3c4a1bb7ce3234407184f0d80cc4dec075e4ad616b44dcc5778e1cfb1b
c24019.woff2
master failed to start, check stderr log for details
```

From `log/unicorn-production.log`:

```
I, [2016-12-31T18:54:48.262181 #27827]  INFO -- : Refreshing Gem list
/home/cubing/worldcubeassociation.org/WcaOnRails/app/models/regulation.rb:4:in `read': No such file or directory @ rb_sysopen - /home/cubing/worldcubeassociation.org/WcaOnRails/app/views/regulations/wca-regulations.json (Errno::ENOENT)
        from /home/cubing/worldcubeassociation.org/WcaOnRails/app/models/regulation.rb:4:in `<class:Regulation>'  
        from /home/cubing/worldcubeassociation.org/WcaOnRails/app/models/regulation.rb:3:in `<top (required)>'
        from /home/cubing/.bundle/ruby/2.3.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /home/cubing/.bundle/ruby/2.3.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
```

The problem is that we cannot start our rails application until we've built the regulations, and our chef script is calling [`startall`](https://github.com/jfly/worldcubeassociation.org/blob/43c5d0f135cc015967680991591c189d8392d107/chef/site-cookbooks/wca/recipes/default.rb#L389) before we execute [`rebuild_regs`](https://github.com/jfly/worldcubeassociation.org/blob/43c5d0f135cc015967680991591c189d8392d107/chef/site-cookbooks/wca/recipes/regulations.rb#L23-L25). `default.rb` runs before `regulations.rb` as specified [here](https://github.com/jfly/worldcubeassociation.org/blob/43c5d0f135cc015967680991591c189d8392d107/chef/roles/wca.json#L34-L37).

I think that the cleanest solution would actually be to rework things a bit so that our rails server can start up with a fresh clone, rather than forcing people to run `rebuild_regs` (this would also allow us to remove the `echo "{}" > WcaOnRails/app/views/regulations/wca-regulations.json` step from our [README](https://github.com/thewca/worldcubeassociation.org#setup)). Then our `regulations.rb` in chef can be updated to do a `rebuild_regs restart_rails`. Otherwise, reordering our chef stuff is going to be a big hassle, and IMO, hard to read.

@viroulep, could you comment on what you think is a good solution?

For now, I've updated https://github.com/thewca/worldcubeassociation.org/wiki/Spinning-up-a-new-server-part-1 with a link to this issue. We should remember to update the wiki after we've addressed this issue.

### PR DESCRIPTION
**Pull request by jfly**
Instead, we have a warning on `/server-status` if anything looks wrong.
This fixes #1063.

## good

image

## bad

image

### CODE REVIEW

File: WcaOnRails/app/controllers/server_status_controller.rb [hunk 1]
```diff
@@ -3,10 +3,18 @@ class ServerStatusController < ApplicationController
...
     @oldest_job_that_should_have_run_by_now = @jobs_that_should_have_run_by_now.order(:created_at).first
+    if @oldest_job_that_should_have_run_by_now
+      @everything_good = false
+    end
 
-    @everything_good = @oldest_job_that_should_have_run_by_now.nil?
+    @regulations_load_error = Regulation.regulations_load_error
+    if @regulations_load_error
+      @everything_good = false
+    end
```
Comment (jonatanklosko) [inline WcaOnRails/app/controllers/server_status_controller.rb]: What about setting it at once?
```ruby
@everything_good = @oldest_job... || @regulations_load_error
```

**Comment by jfly** [comment]
Updated with a test I'm a bit more pleased with. I had to add some testing hooks into the regulation.rb file, but I think it's worth it.

File: WcaOnRails/app/controllers/server_status_controller.rb (hunk 1 above)
Comment (jfly) [inline WcaOnRails/app/controllers/server_status_controller.rb]: Ah, this was actually intentional. I wanted to keep the "is this cause for failure" logic near the rest of the logic for the individual checks. You can imagine that as we add more checks, the single `@everything_good = ....` line will get further and further away from the job logic on the very top. Also, a single line like that is asking for conflicts if 2 different people add checks simultaneously.

**Comment by jonatanklosko** [comment]
LGTM!

File: WcaOnRails/app/controllers/server_status_controller.rb (hunk 1 above)
Comment (larspetrus) [inline WcaOnRails/app/controllers/server_status_controller.rb]: It makes sense to keep each check in it's own section. But I'd prefer this pattern:

`@everything_good &&= @regulations_load_error`

or maybe

`@everything_good &&= @regulations_load_error.present?`

Comment (jfly) [inline WcaOnRails/app/controllers/server_status_controller.rb]: Isn't this logic backwards? If `@regulations_load_error` is truthy, then we want `@everything_good` to be false. I could write it like this if you prefer:

```
@everything_good &&= @regulations_load_error.nil?
```

Comment (larspetrus) [inline WcaOnRails/app/controllers/server_status_controller.rb]: Yes, of course. Off-by-one error.

`.blank?` is possible more robust than `.nil?`

Comment (jfly) [inline WcaOnRails/app/controllers/server_status_controller.rb]: Oh, right, we need to handle the "false" case as well.

On further reflection, I find `blank?` a weird way of checking if something is falsey. I slightly prefer one of these 2 ways to skin this cat:

```
@everything_good &&= !@regulations_load_error.nil?
```

or

```
@everything_good = false if @regulations_load_error
```

I realize this is bikeshedding, but I'm curious what you think nonetheless. Was your preference for just getting this down to 1 line, or did you like the boolean nature of the `&&`?

Comment (larspetrus) [inline WcaOnRails/app/controllers/server_status_controller.rb]: `.nil?` is great if it works. I'm just slightly nervous about `Regulation.regulations_load_error` being changed to return an empty array or even maybe returning false now. With test coverage this doesn't matter, but I'm guessing we don't have that here.

That's probably silly of me. Use `.nil?` if you're confident about it.

I much prefer `&&=` to `false if`

Comment (jfly) [inline WcaOnRails/app/controllers/server_status_controller.rb]: GAH whoops. I had a big typo in my previous post, sorry.

I wrote:

```
@everything_good &&= !@regulations_load_error.nil?
```

when I *meant* to write (that `nil?` isn't suppose to be there):

```
@everything_good &&= !@regulations_load_error
```

Comment (larspetrus) [inline WcaOnRails/app/controllers/server_status_controller.rb]: Aha. That does makes it more falsey-compliant.

Personally I prefer `blah.blank?` to `!blah`, but that's just me, not a universal rule.

Comment (jfly) [inline WcaOnRails/app/controllers/server_status_controller.rb]: I meditated on this for a few moments, and have decided that I like `blank.blank?` now =)
