### PR TITLE
Fix bugs with computing DNF averages and round formats that don't need averages (such as best of 1, 2, 3 (except for 333bf, 333ft, 333fm)).

### LINKED ISSUE #1688: result.rb bugs when computing averages
- [x] multibld should not compute an average
- [x] 333 DNF averages are not getting DNFed
- [x] FMC DNF averages are not getting DNFed

### PR DESCRIPTION
**Pull request by jfly**
This fixes #1688.

### CODE REVIEW

File: WcaOnRails/lib/solve_time.rb [hunk 1]
```diff
@@ -128,10 +128,14 @@ def unskipped?
     !skipped?
   end
 
-  def completed?
+  def complete?
```
Comment (jfly) [inline WcaOnRails/lib/solve_time.rb]: @jonatanklosko, I chose to rename this from `completed?` to `complete?` because `incomplete?` sounds nicer than `incompleted?`.

Comment (jonatanklosko) [inline WcaOnRails/lib/solve_time.rb]: Sounds good =)

File: WcaOnRails/app/models/result.rb [hunk 2]
```diff
@@ -80,16 +80,47 @@ def average_is_not_computable_reason
...
+    #  - 333fm was changed from allowing best of 3 (and disallowing mean of 3) to allowing mean of 3 (and disallowing best of 3).
+    #    See "Relevant regulations changes" below.
+    #    With this change in format, the Board decided to compute means for all
+    #    the old best of 3 rounds, and assign mean records to them.
+    #    However, we could not change the format of the rounds, as that would have affected rankings
+    #    in past competitions, so the rounds remain as best of 3, but with an average computed.
+    #  - 333ft has a similar story to 333fm. It also changed from allowing best of 3
+    #    (and disallowing mean of 3) to allowing mean of 3 (and disallowing best
+    #    of 3). See "Relevant regulations changes" below.
+    #    this event, but fortunately, no competition ever ran 333ft as an average of 5.
```
Comment (jfly) [inline WcaOnRails/app/models/result.rb]: Ah, whoops! That was a typo (leftover sentence I did not fully delete). Good catch =)
