### PR TITLE
Fixes #5623 Validating Scramble Groups = Scramble Sets

### LINKED ISSUE #5623: Result validation for scrambles per round not working
I just noticed that the the two result validation errors that should be forcing delegates to correct the number of scramble sets used at their competitions are actually not working. The most recent result submission for [Hvidovre Sommerhygge 2020](https://www.worldcubeassociation.org/competitions/HvidovreSommerhygge2020) include several mismatches, but no error is thrown.

The relevant code: https://github.com/thewca/worldcubeassociation.org/blob/7297c4e19b40b9df955cbdabf513f2e22ac08368/WcaOnRails/lib/results_validators/scrambles_validator.rb#L50-L63

### PR DESCRIPTION
**Pull request by Jambrose777**
Fixes #5623 

Notes: 
- [x] Adding a test for this later this week (took a bit longer to get my local instance working today than I originally anticipated)
- Changing the Scramble Sets # in the events tab and going back to the Results Uploader runs the validations again without needing to reupload the JSON :D (I didn't know that was a thing!)

Tagging @SAuroux for wording.

### CODE REVIEW

**Comment by viroulep** [comment]
Just a quick FYI: you can open a PR as a "draft", which basically marks it as "WIP"; unfortunately I don't think you can change the status of a PR back to "draft" once it's been open/converted to a "normal" PR (or at least I can't, maybe the author can ?).

File: WcaOnRails/lib/results_validators/scrambles_validator.rb [hunk 1]
```diff
@@ -9,6 +9,8 @@ class ScramblesValidator < GenericValidator
     MISSING_SCRAMBLES_FOR_MULTI_ERROR = "[%{round_id}] While you may have multiple groups in 3x3x3 Multi-Blind, at least one of the groups must contain scrambles for all attempts."
     MULTIPLE_FMC_GROUPS_WARNING = "[%{round_id}] There are multiple groups of FMC used. If one group of FMC was used, please use the Scrambles Matcher to uncheck the unused "\
       "scrambles. Otherwise, please include a comment to WRT explaining why multiple groups of FMC were used."
+    WRONG_NUMBER_OF_SCRAMBLE_SETS_ERROR = "[%{round_id}] Has a different number of scrambles than specified on the Edit Events tab. "\
+      "Please adjust the number of scramble sets in the Edit Events tab to the number of attempts that were used."
```
Comment (SAuroux) [inline WcaOnRails/lib/results_validators/scrambles_validator.rb:13]: I would suggest: 

"[%{round_id}] **This round has** a different number of **scramble sets** than specified on the **Manage** Events tab. Please adjust the number of scramble sets in the **Manage** Events tab to the number of **sets** that were used."

**Comment by Jambrose777** [comment]
> Just a quick FYI: you can open a PR as a "draft", which basically marks it as "WIP"; unfortunately I don't think you can change the status of a PR back to "draft" once it's been open/converted to a "normal" PR (or at least I can't, maybe the author can ?).

Ya, I was trying to make it a draft PR after posting it, but it looks like that can only be done when creating it. :P (I'm also used to gitlab where putting WIP in the title does that kind of thing automatically). Nevertheless, this PR is ready assuming the build passes after my most recent push :D

**Comment by Jambrose777** [comment]
Any chance this can get reviewed?

**Review by jonatanklosko — APPROVED** [review]
LGTM, thanks!
