### PR TITLE
Fix record history by region

### LINKED ISSUE #11462: Record history by Country broken
Just noticed this. Error in new relic is Mysql2::Error: Unknown column 'results.country_id' in 'where clause' so this is renaming related?

### PR DESCRIPTION
**Pull request by dunkOnIT**
Fixes #11462 

Currently, [record history by region](https://www.worldcubeassociation.org/results/records?region=_Africa&show=history) is broken in prod. I replicated this issue locally through tests, and fixed it by correcting what appears to be inconsistent table aliases in the SQL queries.

I have added parametrized tests to cover the basic cases that were failing - there is more that can be done here though.

Follow-up PR: This section of the code is severely under-tested. Add more tests against the results API endpoints we use in production. Specifically:
- [ ] Add 3 and 4-parameter tests
- [ ] Add all cases of 2-parameter tests (currently we're only testing combinations of `show` and `region` - but we should ideally test all combinations of 
- [ ] We _possibly_ don't always return errors when an incorrect value is supplied (this may just be an error in my tests at the time of writing them, not an error with the code) - investigate this and raises tests/fix if necessary
- [ ] We don't raise errors if unexpected parameters are supplied (eg, 'event' instead of 'event_id') - perhaps not the end of the world, but leads to false-positives when testing

It is particularly important to make sure the test fails first, to ensure that you are actually triggering the behaviour you expect. (For example, in this PR, my test database was incompletely populated, and so wasn't triggering the region-specific code. I would not have picked this up if not for the fact that this use case was failing in production but not under my testing.)

### CODE REVIEW

**Comment by pranav-027** [comment]
I tried this approach, it definitely fixes the history and mixed history filter, but breaks the other 'non-history' filters mixed and slim.

Because, in non-history queries, we query the results table directly, and in history queries, we query from a UNION subquery aliased as `result`.  So I just renamed the alias to `results` https://github.com/thewca/worldcubeassociation.org/pull/11463

**Comment by dunkOnIT** [comment]
Ah ok I see! Definitely evidence for the fact that we need tests against these endpoints

**Review by gregorbg — CHANGES_REQUESTED** [review]
The "cleaner" (i.e., more consistent) fix here is actually to change the SQL query to use `results` with plural S as an alias.

Rationale: We're already using `results` as a table name and as an alias for the concise tables in all other queries throughout the controller. It's only the regional record query that (inconsistently) uses `result` in singular form. Changing the filter's expected alias to `result` would fix the regions query but it breaks all other query types in return.

File: app/controllers/results_controller.rb [hunk 1]
```diff
@@ -176,12 +178,11 @@ def records
     params[:show] ||= SHOW_MIXED
     params[:gender] ||= GENDER_ALL
 
-    @shows = [SHOW_MIXED, "slim", "separate", "history", "mixed history"]
```
Comment (dunkOnIT) [inline app/controllers/results_controller.rb:179]: Moved this definition into a constant on new-line 7

File: spec/support/test_constants.rb [hunk 2]
```diff
@@ -0,0 +1,6 @@
+# frozen_string_literal: true
+
+module TestConstants
+  RESULT_TEST_EVENTS = %w[333 333mbf 333fm].freeze
+  RESULT_TEST_REGIONS = ['_Africa', 'South Africa'].freeze
```
Comment (gregorbg) [inline spec/support/test_constants.rb:5]: Hm, I wonder who might have come up with these values...?

File: app/controllers/results_controller.rb [hunk 3]
```diff
@@ -4,6 +4,8 @@ class ResultsController < ApplicationController
   REGION_WORLD = "world"
   YEARS_ALL = "all years"
   SHOW_100_PERSONS = "100 persons"
+  SHOWS = ['mixed', 'slim', 'separate', 'history', 'mixed history'].freeze
```
Comment (gregorbg) [inline app/controllers/results_controller.rb:7]: I think RuboCop doesn't like this...?

**Review by gregorbg — APPROVED** [review]

File: app/controllers/results_controller.rb (hunk 3 above)
Comment (dunkOnIT) [reply app/controllers/results_controller.rb:7]: I was also expecting it to correct it, but I think because `mixed history` has a space it's fine with not using %w? It clearly didn't complain in CI, at any rate :P
