### PR TITLE
Shared cumulative time limits fix

### LINKED ISSUE #6502: Cumulative Limit Shared Between Rounds Bug
**Describe the bug**
Whenever changing a cumulative limit that is shared with another round, the shared aspect glitches out.

**To Reproduce**
1. Go to '/competitions/{competitionId}/events/edit'
2. Add 2 events with 1 round each. Ie. Click 'Add Event' next to 4x4x4 Blindfolded and 5x5x5 Blindfolded. Then for each event select 1 Round in the dropdown menu.
3. Click the box for 'Time Limit'
4. Set up a Shared Cumulative Limit. Ie. Click the Cumulative Radio Button. Click 'Share with other Rounds'. Select the other Round created.
**Notice** Under the explaination text, 5x5x5 Blindfolded Round 1 is listed as a round that the cumulative limit is shared with (see Screenshot 1).
5. Click Ok.
**Notice** The time limit list the events and rounds for the shared cumulative limit.
6. Reclick the box for 'Time Limit' (Same as step 3).
7. Click Ok. - **This is where the Bug happens.**

- The Time Limit now no longer list that it is shared.
- If you open The Time limit editor box back up, 5x5x5 Blindfolded is no longer listed under the explanation text.
- If you then Click the 'share with other rounds' Button, 5x5x5 Blindfolded is already checked to share the limit with! (Screenshot 2)
- At that point you have to deselect 5x5x5 Blindfolded, press ok, then reopen the share with other rounds menu and reselect it in order to readd it.

**Expected behavior**
The cumulative Time limit should still be shared whenever editing the time limit for an event.

**Screenshots**
image
image

**Additional context**
For Delegates/Organizers Deselecting and Reselecting the event the time limit is shared with is easy enough, but this can easily slide under the radar and the person editing the event not even realize that the events page will no longer say the time limit is shared.

### PR DESCRIPTION
**Pull request by kr-matthews**
Resolves #6502.

## There were a few problems
1. When updating a shared cumulative time limit, those shared rounds (and the round itself) were not updated properly (as reported in #6502).
2. When changing from a shared cumulative time limit to a per solve time limit, those shared rounds were not updated.
3. When removing rounds which were part of a shared time limit, those shared rounds were not updated.
4. When deleting events which had rounds which were part of a shared time limit, those shared rounds were not updated.

## Example of current behaviour
If there are the following shared time limits:
- 2x2, 3x3, 4x4, 5x5
- 6x6, 7x7, clock, mega

And then 5x5 is changed to share with 4x4, 6x6, 7x7, and pyra, then the new shared time limits will be:
1. 2x2, 3x3
2. clock, mega
3. 4x4, 5x5, 6x6, 7x7, pyra

(Previously, this would show 2x2 and 3x3 in a group of 2x2, 3x3, 4x4, 5x5, and incompatibly show 4x4 and 5x5 in a group of 4x4, 5x5, 6x6, 7x7, pyra.)

Screenshot from 2022-01-15 16-44-52
Screenshot from 2022-01-15 16-53-39
Screenshot from 2022-01-15 17-06-47

### CODE REVIEW

File: WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js [hunk 1]
```diff
@@ -20,11 +20,9 @@ let RoundAttributeComponents = {
...
 };
 
-function findRoundsSharingTimeLimitWithRound(wcifEvents, wcifRound) {
-  return _.compact(_.flatMap(wcifEvents, 'rounds')).filter(otherWcifRound =>
-    otherWcifRound !== wcifRound
-    && otherWcifRound.timeLimit
-    && otherWcifRound.timeLimit.cumulativeRoundIds.includes(wcifRound.id)
+export function removeRoundsFromSharedTimeLimits(wcifEvents, wcifRounds) {
+  _.compact(_.flatMap(wcifEvents, 'rounds')).forEach(otherWcifRound =>
+    _.pull(otherWcifRound.timeLimit.cumulativeRoundIds, ...wcifRounds)
```
Comment (gregorbg) [inline WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:25]: Nitpick: As opposed to the previous `findRoundsSharingTimeLimitWithRound` function, you are now implicitly modifying the `wcifEvents` parameter in-place.

Please document that fact very clearly. If it's not too much of a hassle, try thinking of a way that the exported function doesn't `_.pull` by itself, but rather returns the events that have to be pulled, so that every React component can modify its own state/props based on the return value of this method.

**Review by gregorbg — COMMENTED** [review]
Very thorough implementation, thanks a lot! Just one comment about the `removeRoundsFromSharedTimeLimits` method, though I'm not sure whether that's severe enough to block the entire PR. Let me know what you think!

File: WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js (hunk 1 above)
Comment (kr-matthews) [reply WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:25]: I see what you mean. But the components using this helper already have the events that need to be pulled; they're passed in as the parameter `wcifRounds`. Doing what you suggest would basically amount to copy-pasting this helper function into any other component which uses it, unless I'm missing something.
I'm guessing it would be better to add a comment to the current state of the code, as opposed to having two copies of the same function in different files with some comments explaining why?

Comment (gregorbg) [reply WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:25]: If the alternative would really just amount to copy-pasting, then adding a comment to this method and leaving as-is will be fine.

Comment (kr-matthews) [reply WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:27]: Added comments here and with the import.

Comment (gregorbg) [reply WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:27]: Thanks!
(a) Is there something like "documentation comments" in JavaScript? For example, in Java `// this is a general comment` and `/** This is a documentation comment */`.
(b) Please refrain from adding comments in the imports section, nobody ever reads these. Instead, add a comment at the call-site if necessary. I think changing the method comment to a proper documentation comment as per (a) will suffice.

Comment (kr-matthews) [reply WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:27]: (a) Yes, seems like it, see [wikipedia](https://en.wikipedia.org/wiki/JSDoc).
(b) Ok makes sense. Something like this?
```
/**
 * Finds the cumulativeRoundIds of each event in wcifEvents and removes any
 * which are found in wcifRounds. Note that it modifies wicfEvents in place.
 *
 * @param {collection} wcifEvents Will be modified in place.
 * @param {Array}      wcifRounds Rounds to be removed from all cumulativeRoundIds.
 */
 ```

Comment (gregorbg) [reply WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:27]: Yup, something along those lines :)

Comment (kr-matthews) [reply WcaOnRails/app/webpacker/javascript/edit-events/modals/index.js:32]: Done. Thanks for bringing comments vs documentation to my attention.

**Review by gregorbg — APPROVED** [review]
