### PR TITLE
Fix DNS/DNF Ordering and wrong positions being shown

### LINKED ISSUE #13999: Results with DNS have pos being shown as 1
Image

Finn's comments: 
I think 1 is somehow the default when displaying
[10:40 AM]Remember when there were random 1s in the middle when I didn't set global pos for both yet?
[10:41 AM]Definitely a front-end bug

Backend payload shows correct pos: 
Image

### PR DESCRIPTION
**Pull request by FinnIckler**
DNF/DNS ordering was fixed by adding an extra `(aInvalid && bInvalid)` branch. The wrong positions was actually because I was using map and then acessing the original array. Switching to reduce instead fixed it. 

This will fix #13999 and probably even #13900

I also added a bunch of test data for tests. This is straight out of the developer console. We do not really have a procedure set up for fixtures, but I didn't want to set up some custom factory libraries or something just for these tests.

### CODE REVIEW

**Comment by FinnIckler** [comment]
Now that I think about it, a DNS best is actually not possible so I should just need the reduce changes

File: next-frontend/src/lib/live/orderResults.ts [hunk 1]
```diff
@@ -34,19 +34,22 @@ export const orderResults = (results: LiveResult[], format: Format) => {
...
-    if (index === 0) {
-      return { ...result, global_pos: 1 };
-    }
-
-    const prev = arr[index - 1];
+  return sortedResults.reduce<(LiveResult & { global_pos: number })[]>(
+    (acc, result, index) => {
+      if (index === 0) {
+        acc.push({ ...result, global_pos: 1 });
+        return acc;
```
Comment (gregorbg) [inline next-frontend/src/lib/live/orderResults.ts]:
```suggestion
        return {
          ...acc,
          { ...result, global_pos: 1 }
        };
```

File: next-frontend/src/lib/live/orderResults.ts [hunk 2]
```diff
@@ -34,19 +34,22 @@ export const orderResults = (results: LiveResult[], format: Format) => {
...
 
-    const global_pos = isTied ? prev.global_pos : index + 1;
+      const isTied =
+        result[rankBy] === prev[rankBy] &&
+        (!secondaryRankBy || result[secondaryRankBy] === prev[secondaryRankBy]);
 
-    return { ...result, global_pos };
-  });
+      acc.push({ ...result, global_pos: isTied ? prev.global_pos : index + 1 });
+      return acc;
```
Comment (gregorbg) [inline next-frontend/src/lib/live/orderResults.ts]:
```suggestion
      return {
        ...accm
        { ...result, global_pos: isTied ? prev.global_pos : index + 1 },
      };
```

**Review by gregorbg — CHANGES_REQUESTED** [review]
No `push` please 🙃

File: next-frontend/src/lib/live/orderResults.ts (hunk 2 above)
Comment (FinnIckler) [reply next-frontend/src/lib/live/orderResults.ts]: you mean [...acc]

**Review by gregorbg — APPROVED** [review]
