### PR TITLE
Set expiry date of credit card to 2030 for refund test - Fixes #2357

### LINKED ISSUE #2357: Testing refunds with 2017 credit card fails
The current test for refunds creates a dummy credit card with a 2017 expiry date which is no longer valid in 2018!

### PR DESCRIPTION
**Pull request by pingskills**
Now we are in 2018, a credit card with an expiry date of 2017 is not valid.

### CODE REVIEW

File: WcaOnRails/spec/controllers/registrations_controller_spec.rb [hunk 1]
```diff
@@ -679,7 +679,7 @@ def stripe_token_id(options = {})
           card: {
             number: "4242424242424242",
             exp_month: 12,
-            exp_year: 2017,
+            exp_year: 2030,
```
Comment (jfly) [inline WcaOnRails/spec/controllers/registrations_controller_spec.rb]: Possibly insane future proofing, but we `Date.today.year + 1` feels a little less arbitrary to me. Although I would love to run into this problem again in 2031 =) Whichever you prefer!
