### PR TITLE
Fix results announcement to handle ties

### LINKED ISSUE #2737: Incorrect announcement with tied rankings
I and Ziheng Ma tied on the 3x3x3 fewest moves. But the generated announcement was incorrect. See the following pics.

image
image

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #2737.

### CODE REVIEW

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 1]
```diff
@@ -246,23 +255,25 @@ def post_results
         if top_three.empty?
           return render html: "<div class='container'><div class='alert alert-warning'>Nobody competed in event: #{event.id}</div></div>".html_safe
         else
-          first_result = top_three.first
+          results_by_place = top_three.group_by(&:pos)
+          winners = results_by_place[1]
 
-          title = "#{first_result.personName} wins #{comp.name}, in #{comp.cityName}, #{comp.country.name}"
+          title = "#{people_to_sentence(winners, link: false)} #{winners.length  > 1 ? "win" : "wins"} " \
```
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Nit: I think there are two spaces before the `>` here.

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 2]
```diff
@@ -246,23 +255,25 @@ def post_results
...
-              body += " and [#{top_three.third.personName}](#{person_url top_three.third.personId}) finished third (#{pretty_print_result(top_three.third, short: true)})"
-            end
+          body += "."
+          if results_by_place[2]
+            body += " #{people_to_sentence(results_by_place[2], link: true)} finished second (#{pretty_print_result(top_three.second, short: true)})"
+            body += results_by_place[3] ? " and" : "."
           end
-
-          body += ".\n\n"
+          if results_by_place[3]
```
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: Out of curiosity, can this happen if the previous `if results_by_place[2]` did not happen? Or did you just move this out here to reduce indentation?

File: WcaOnRails/app/controllers/competitions_controller.rb [hunk 3]
```diff
@@ -246,23 +255,25 @@ def post_results
...
+            body += " #{people_to_sentence(results_by_place[3], link: true)} finished third (#{pretty_print_result(top_three.third, short: true)})"
+            body += "."
+          end
+          body += "\n\n"
```
Comment (jfly) [inline WcaOnRails/app/controllers/competitions_controller.rb]: I am surprised that you moved the period away from here. Was that necessary, or do you just prefer the way you've written in here?

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 1 above)
Comment (jonatanklosko) [reply WcaOnRails/app/controllers/competitions_controller.rb]: Good eye! Travis didn't hesitate to point this out as well ^^
```

app/controllers/competitions_controller.rb:261:80: C: Layout/ExtraSpacing: Unnecessary spacing detected.
          title = "#{people_to_sentence(winners, link: false)} #{winners.length  > 1 ? "win" : "wins"} " \
                                                                               ^
```

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 2 above)
Comment (jonatanklosko) [reply WcaOnRails/app/controllers/competitions_controller.rb]: This can surely be the case, you can even see it in the test where two people take the first place, so there are two `1st` places, one `3rd` place, but no `2nd` places at all.

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 3 above)
Comment (jonatanklosko) [reply WcaOnRails/app/controllers/competitions_controller.rb]: Not saying there are no other ways, but this one seemed ok. There is `body += "."` before both `if` statements, so if three people would tie the first place then both conditionals would be skipped and you'd end up with two dots at the end.

File: WcaOnRails/app/controllers/competitions_controller.rb (hunk 2 above)
Comment (jfly) [reply WcaOnRails/app/controllers/competitions_controller.rb]: Oh, right! Silly ties :)
