### PR TITLE
Fix sorting countries in forms

### LINKED ISSUE #1384: Countries list is not sorted correctly by local language in sign_up page
This problem is related to i18n.
Countries list in the form in [sign_up page](https://www.worldcubeassociation.org/users/sign_up) (in "I have never competed in a WCA competition." tab) is not sorted correctly, while the list in the [competitions page](https://www.worldcubeassociation.org/competitions) is sorted properly.

In French page for example (but wrong order in almost all languages), I suppose it's sorted by English order:

I guess we can deal with this problem using `ALL_COUNTRIES_WITH_NAME_AND_ID_BY_LOCALE` (defined [here](https://github.com/thewca/worldcubeassociation.org/blob/3a86270c5df7426336bebf0cb365f180a8abdcec/WcaOnRails/app/models/country.rb#L68)) or something like that, but I don't understand WCA website technical things so much, so I hope someone will fix this.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #1384.

Currently the constant includes `[localized_name, id]` pairs, which is not general enough to fit the forms, so what I did is to have the whole arrays of `Country` objects instead.

Also it's quite tricky as currently we have *all* countries stored in the constant, whereas in the forms we just need the *real* ones (i.e. not *Multiple Countries (...)*), so additional `select` was necessary.

That's the first reasonable idea that crossed my mind, let me know if you can think of any better way of tackling this issue.

### CODE REVIEW

File: WcaOnRails/app/models/country.rb [hunk 1]
```diff
@@ -65,16 +69,8 @@ def self.localized_sort_by!(wca_locale, array, &block)
     array.sort_by! { |element| collator.get_sort_key(block.call(element)) }
   end
 
-  ALL_COUNTRIES_WITH_NAME_AND_ID_BY_LOCALE = Hash[I18n.available_locales.map do |locale|
-    countries = localized_sort_by!(locale, Country.all.map do |country|
-      # We want a localized country name, but a constant id across languages
-      # NOTE: it means "search" will behave weirdly as it still searches by English
-      # name (eg: searching for "Tunisie" in French won't match competitions in
-      # "Tunisia" even if the country displayed is actually "Tunisie"...)
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/country.rb]: @viroulep What does the `"search"` refer to?

File: WcaOnRails/app/models/country.rb [hunk 2]
```diff
@@ -65,16 +69,8 @@ def self.localized_sort_by!(wca_locale, array, &block)
...
-      [country.name_in(locale), country.id]
-      # Now we want to sort countries according to their localized name
-    end) { |localized_name, _id| localized_name }
-
+  ALL_COUNTRIES_BY_LOCALE = Hash[I18n.available_locales.map do |locale|
```
Comment (larspetrus) [inline WcaOnRails/app/models/country.rb]: - I think that within the `Country` class we can assume the context is countries.
- The purpose should be made clear.

So I'd name this `ALL_SORTED_BY_LOCALE`

File: WcaOnRails/app/views/devise/registrations/new.html.erb [hunk 3]
```diff
@@ -46,7 +46,7 @@
             <%= f.input :name %>
             <%= f.input :dob, as: :date_picker %>
             <%= f.input :gender, collection: User::ALLOWABLE_GENDERS, label_method: lambda { |g| { m: t('wca.devise.gender.male'), f: t('wca.devise.gender.female'), o: t('wca.devise.gender.other_gender') }[g] } %>
-            <%= f.input :country_iso2, collection: Country.real, value_method: lambda { |c| c.iso2 }, label_method: lambda { |c| c.name } %>
+            <%= f.input :country_iso2, collection: Country::ALL_COUNTRIES_BY_LOCALE[I18n.locale].select(&:real?), value_method: lambda { |c| c.iso2 }, label_method: lambda { |c| c.name } %>
```
Comment (larspetrus) [inline WcaOnRails/app/views/devise/registrations/new.html.erb]: I'd make a method hiding some of these unseemly details. Could look like this:

`Country::all_sorted_by(I18n.locale, real: true), value_method: ...`

File: WcaOnRails/app/models/country.rb (hunk 2 above)
Comment (jonatanklosko) [inline WcaOnRails/app/models/country.rb]: Good idea!

File: WcaOnRails/app/views/devise/registrations/new.html.erb (hunk 3 above)
Comment (jonatanklosko) [inline WcaOnRails/app/views/devise/registrations/new.html.erb]: That's great =)

**Comment by larspetrus** [comment]
I forgot the pre-LGTM before.

File: WcaOnRails/app/models/country.rb (hunk 1 above)
Comment (viroulep) [inline WcaOnRails/app/models/country.rb]: That's actually a deprecated comment!
When I initially made it we could input a country name in the competitions list page, now we only use the dropdown :)

File: WcaOnRails/app/models/country.rb [hunk 4]
```diff
@@ -20,6 +20,10 @@ def self.real
     @real_countries ||= Country.uncached_real
   end
 
+  def real?
+    !read_attribute(:name).include?('Multiple Countries')
```
Comment (viroulep) [inline WcaOnRails/app/models/country.rb]: What about using an array of iso codes ? (like `%w(XA XE XS)`)
Your way definitely works, but I feel like being explicit would be clearer.

Comment (jonatanklosko) [inline WcaOnRails/app/models/country.rb]: Neat idea, I'd do the same for  the `real` scope!

**Comment by jonatanklosko** [comment]
@viroulep I just did so! I sticked to a constant for Continents as the method wouldn't bring any new logic and would be simply redundant.
Also I moved the sorting logic out of the `Continent` model, because it awkward to keep it there, especially with this long comment

File: WcaOnRails/app/models/country.rb [hunk 5]
```diff
@@ -6,7 +6,7 @@ class Country < ApplicationRecord
   belongs_to :continent, foreign_key: :continentId
   has_many :competitions, foreign_key: :countryId
 
-  scope :uncached_real, -> { where("name not like 'Multiple Countries%'") }
+  scope :uncached_real, -> { where.not(id: %w(XA XE XS)) }
```
Comment (viroulep) [inline WcaOnRails/app/models/country.rb]: Didn't notice we had a similar test here!
Then I think a frozen static array (that we would use in both places) would be better: just because if we need to change this array for some reason, then we wouldn't forget about changing it else where!

**Comment by viroulep** [comment]
Yeah it's ok :)

I just left one last comment but appart from that LGTM!
