### PR TITLE
When a missing interpolation key is found for a non :en locale, don't raise an error.

### LINKED ISSUE #1259: Outdated translations can crash individual pages
So, the /edit/admin page doesn't load for me in locale: es.

Here's what I see on the server logs:

```
F, [2017-02-01T02:45:07.764810 #26469] FATAL -- :
ActionView::Template::Error (missing interpolation argument :comps in "%{comps} %{comp} en %{kms} km y %{days} días." ({:x_competitions=>"9 competitions", :kms=>200, :days=>365} given)):
    35:     <div class="col-sm-9">
    36:       <% nearby_competitions_info = @competition.nearby_competitions(Competition::NEARBY_DAYS_INFO, Competition::NEARBY_DISTANCE_KM_INFO).sort_by(&:start_date) %>
    37:       <% nearby_count = nearby_competitions_info.count %>
    38:       <div class="alert <%= nearby_count < Competition::NEARBY_INFO_COUNT ? "alert-success" : "alert-danger" %>" role="alert"><%= t '.nearby_admin', x_competitions: t('.competitions', count: nearby_count), kms: Competition::NEARBY_DISTANCE_KM_INFO, days: Competition::NEARBY_DAYS_INFO %>
    39:       <button type="button" class="btn" data-toggle="modal" data-target="#competitions-last-year-modal"><%= t '.show' %></button>
    40:       </div>
    41:     </div>
  app/views/competitions/_nearby_competitions.html.erb:38:in `_app_views_competitions__nearby_competitions_html_erb__2076549207874311778_128092340'
  app/views/competitions/_competition_form.html.erb:207:in `block in _app_views_competitions__competition_form_html_erb__2399980640299519409_103775980'
  app/helpers/application_helper.rb:151:in `block in simple_form_for'
  app/helpers/application_helper.rb:150:in `simple_form_for'
  app/helpers/application_helper.rb:168:in `horizontal_simple_form_for'
  app/views/competitions/_competition_form.html.erb:3:in `_app_views_competitions__competition_form_html_erb__2399980640299519409_103775980'
  app/views/competitions/edit.html.erb:18:in `block in _app_views_competitions_edit_html_erb__3953575044078717486_134356900'
  app/views/competitions/_nav.html.erb:193:in `_app_views_competitions__nav_html_erb__2462345723200062896_66947420'   
  app/views/competitions/edit.html.erb:3:in `_app_views_competitions_edit_html_erb__3953575044078717486_134356900'
  app/controllers/competitions_controller.rb:279:in `admin_edit'
  lib/middlewares/warden_user_logger.rb:12:in `call'
  lib/middlewares/fix_accept_header.rb:13:in `call'
```

And if you check https://www.worldcubeassociation.org/server-status, you will see that the competitions > nearby_competitions > nearby_admin key is out of date, which is probably what's causing this error.

It's rather unfortunate that an out of date translation can effectively crash our website. It would be cool if we fell back to English for these cases, or even just inserted an empty string or some warning instead. Any ideas for working around this?

Crazy idea #1: define our own "t" method that catches this error and rerenders in English. If English crashes, that's a-okay, we did our best.

@viroulep said:

This [commit](https://github.com/thewca/worldcubeassociation.org/commit/7a416030a90394359835268be993f1c8d7685a9a) introduced the variables changes in the key, and you can see that the Spanish one has been forgotten!

The crazy idea sounds fun, but this can enforced statically so we can just add a test for this!

@jfly wonders:

That sounds even better! Do you mean "in theory" it can be enforced statically, or is there already a tool for this? Looking through i18n-tasks, I see https://github.com/glebm/i18n-tasks/issues/192, which is still open =(

### PR DESCRIPTION
**Pull request by jfly**
Instead, just report it missing. This fixes #1259.

Some digging led me to this handy [`missing_interpolation_argument_handler=` method](https://github.com/svenfuchs/i18n/blob/v0.7.0/lib/i18n/config.rb#L107), called from [here](https://github.com/svenfuchs/i18n/blob/v0.7.0/lib/i18n/interpolate/ruby.rb#L29).

## Testing it out

With this change:

```
~/gitting/worldcubeassociation.org/WcaOnRails @kaladin> git diff
diff --git a/WcaOnRails/config/locales/en.yml b/WcaOnRails/config/locales/en.yml
index cb2815ef..6bbb50ad 100644
--- a/WcaOnRails/config/locales/en.yml
+++ b/WcaOnRails/config/locales/en.yml
@@ -683,7 +683,7 @@ en:
       create_success: "Successfully created new competition!"
       results_preview_alert: "You are viewing results that have not been posted yet."
       upload_results: "This competition is over, we are working to upload the results as soon as possible!"
-      in_progress: "This competition is ongoing. Come back after %{date} to see the results!"
+      in_progress: "This competition is ongoing. %{jeremytest} Come back after %{date} to see the results!"
       tooltip_registered: "You are registered."
       tooltip_waiting_list: "You are currently on the waiting list."
       confirmed_visible: "This competition is confirmed and visible"
diff --git a/WcaOnRails/config/locales/es.yml b/WcaOnRails/config/locales/es.yml
index b1cc7c88..9add245c 100644
--- a/WcaOnRails/config/locales/es.yml
+++ b/WcaOnRails/config/locales/es.yml
@@ -1224,7 +1224,7 @@ es:
         sus resultados cuanto antes.
       #original_hash: a0168ee
       in_progress: >-
-        Esta competición se está celebrando ahora. Vuelve después de %{date}
+        Esta competición se está celebrando ahora. %{jeremytest} Vuelve después de %{date}
         para consultar sus resultados.
       #original_hash: 3322400
       tooltip_registered: Estás registrado.
```

### I see the following in Spanish:

image

### But it still crashes in English (as desired):

image

### CODE REVIEW

File: WcaOnRails/config/initializers/i18n_ignore_missing_interpolation_argument.rb [hunk 1]
```diff
@@ -0,0 +1,10 @@
+I18n.config.missing_interpolation_argument_handler = Proc.new do |missing_key, provided_hash, string|
+  if I18n.locale == :en
+    # We only want to raise exceptions for English. This allows development to continue
+    # in English, without being held up by slow translations.
+    #  https://github.com/thewca/worldcubeassociation.org/issues/1259
+    raise MissingInterpolationArgument.new(missing_key, provided_hash, string)
+  else
+    "UNKNOWN_INTERPOLATION_KEY_FOUND_IN_TRANSLATION (#{missing_key})"
```
Comment (jfly) [inline WcaOnRails/config/initializers/i18n_ignore_missing_interpolation_argument.rb]: We don't have enough context here to fall back to English, as I had originally hoped to implement this. However, I think this solution is fine.

**Comment by jfly** [comment]
I plan to merge this on Friday if no one objects before then.

**Comment by viroulep** [comment]
Too bad we don't have the key name and scope in the exception :(
At least it will be pretty clear that something is not normal!

LGTM

**Comment by jfly** [comment]
> Too bad we don't have the key name and scope in the exception :(

Yes, that is very disappointing!

Thanks for taking a look. Merging this up now =)
