### PR TITLE
Fix the rendering of 333mbo results

### LINKED ISSUE #6456: 333mbo results display incorrectly in webpacker
Results for 333mbo on competitions pages, rendered by webpacker, don't parse the time correctly.  See for example https://www.worldcubeassociation.org/competitions/GermanOpen2007/results/all?event=333mbo.

241289729_1482795598763213_8291636496501069559_n

The issue is that app/webpacker/javascript/wca-live/attempts.js does not have logic to parse 333mbo results, it assumes that all multi-blind results use the new-style format.

### PR DESCRIPTION
**Pull request by timreyn**
Adds logic to the webpacker implementation to parse 333mbo results
correctly.

Fixes #6456.

### CODE REVIEW

File: WcaOnRails/app/webpacker/javascript/wca-live/attempts.js [hunk 1]
```diff
@@ -25,11 +28,19 @@ function centisecondsToClockFormat(centiseconds) {
  */
 function decodeMbldAttemptResult(value) {
   if (value <= 0) return { solved: 0, attempted: 0, centiseconds: value };
-  const missed = value % 100;
-  const seconds = Math.floor(value / 100) % 1e5;
-  const points = 99 - (Math.floor(value / 1e7) % 100);
-  const solved = points + missed;
-  const attempted = solved + missed;
+  if (value < 1e9) { // New-style result.
```
Comment (gregorbg) [inline WcaOnRails/app/webpacker/javascript/wca-live/attempts.js:31]: This if-check hides the actual design decision behind the format, that is "results starts with a 1".

Even though your approach might be computationally efficient, I would rather write something along the lines of `value.toString().startsWith('1')` for the sake of clarity/readability.

Comment (gregorbg) [reply WcaOnRails/app/webpacker/javascript/wca-live/attempts.js:31]: Additional nitpick: I would have the if-query check whether or not it is an _old_ style result, and treat the new-style result as the "default assumption" below the if.

On that note, maybe extract the if-condition into its own `isOldStyleResult` variable and then use it through `if (isOldStyleResult)`

**Review by gregorbg — CHANGES_REQUESTED** [review]
Thank you for your contribution! Just some minor nitpicks :)

File: WcaOnRails/app/webpacker/javascript/wca-live/attempts.js (hunk 1 above)
Comment (timreyn) [reply WcaOnRails/app/webpacker/javascript/wca-live/attempts.js]: Done.  For the first suggestion, I padded it to a 10-digit number first (otherwise if someone gets 80+ points this logic treat it as an old-style result).

File: WcaOnRails/app/webpacker/javascript/wca-live/attempts.js [hunk 2]
```diff
@@ -6,6 +6,9 @@ export const DNS_VALUE = -2;
  * Converts centiseconds to a human-friendly string.
  */
 function centisecondsToClockFormat(centiseconds) {
+  if (centiseconds == null) {
+    return '?:??:??';
```
[the remark this answers is not in the document]
Comment (timreyn) [reply WcaOnRails/app/webpacker/javascript/wca-live/attempts.js:10]: Yes -- the competition linked in the issue I filed (https://www.worldcubeassociation.org/competitions/GermanOpen2007/results/all?event=333mbo) has many results without a time.  I'll send this to WRT (though I'll wait till this PR goes live since it'll be clearer then :) )

**Review by gregorbg — APPROVED** [review]
Thanks for your prompt fixes!

**Comment by gregorbg** [comment]
Sidenote: The Coveralls API is currently undergoing maintenance, which is why our CI fails.
Will merge this as soon as Coveralls is up-and-running again, otherwise we will provoke an unnecessary high amount of "CI failed" notifications.
