### PR TITLE
Change message for too many wca id claims. Fixes #3870

### LINKED ISSUE #3870: Change the Message for too many WCAID claims
All WRT has done so far is ask the person to fill out the incorrect DOB form (which may benefit by being reworked to a data correction form). 
I made a comment on the code here:
https://github.com/thewca/worldcubeassociation.org/pull/3666#discussion_r253315031

### PR DESCRIPTION
**Pull request by Goosly**
(At least I think so :p)

### CODE REVIEW

**Comment by viroulep** [comment]
Thanks for the PR Manu, I think it does but you forgot to adjust the existing tests, so I fixed it and pushed the commit to your branch!

By the way you may want to make PRs from dedicated branches of your repository instead of from the master branch: when submitting a PR to the WCA repo you give push access to the repo maintainers (unless you uncheck the option).
Whereas maybe you would like to keep a clean master branch on your repo that matches the WCA's repo.

File: WcaOnRails/spec/features/claim_wca_id_spec.rb [hunk 1]
```diff
@@ -87,7 +87,9 @@
       fill_in "Birthdate", with: "1988-02-03"
       click_button "Claim WCA ID"
 
-      expect(page.find(".alert.alert-danger")).to have_content("There have been too many incorrect claims for this WCA ID. Please contact the WCA Results Team to resolve this.")
+      # Based on WRT request here: https://github.com/thewca/worldcubeassociation.org/pull/3666#discussion_r253315031,
+      # the expected message for this is users.errors.wca_id_no_birthdate_html
+      expect(page.find(".alert.alert-danger")).to have_content("We do not have a birthdate recorded for this WCA ID. Please contact the WCA Results Team")
```
Comment (jfly) [inline WcaOnRails/spec/features/claim_wca_id_spec.rb]: Not a huge deal, but this feels like weird text to show people... it's not that we don't have a birthdate recorded, it's that the birthdate is probably wrong. I think a message like this would make more sense:

> There have been too many incorrect claims for this WCA ID, so we've locked this id to prevent future attempts to claim it. It's possible we have the wrong date of birth on file. Please contact the WCA Results Team using <a href=\"%{dob_form_path}\">this dedicated form</a>.

Comment (viroulep) [reply WcaOnRails/spec/features/claim_wca_id_spec.rb]: I'd definitely agree with that, though you actually said it sounded good to you [there](https://github.com/thewca/worldcubeassociation.org/pull/3666#discussion_r253337865) :p

Basically I'd use whatever the WRT thinks it's best here.

**Comment by Goosly** [comment]
Thanks for the explanation. I guess I should read some documentation on the usage of PR's in Github. I'm used to just commit & push stuff 99% of the time :-)

File: WcaOnRails/spec/features/claim_wca_id_spec.rb (hunk 1 above)
Comment (jfly) [reply WcaOnRails/spec/features/claim_wca_id_spec.rb]: Haha, yeah, I didn't think through this when I wrote that comment :cry:
