### PR TITLE
Fix live results not meeting cutoff being seen as incomplete

### LINKED ISSUE #14152: People who didn't make cutoff marked as advanced even when they are worse than people who are advanced
https://www.worldcubeassociation.org/competitions/MunichOpen2026/live/rounds/sq1-r1

### PR DESCRIPTION
**Pull request by FinnIckler**
The `best != 0 && round.cutoff.present? && !round.cutoff.apply(live_attempts)` got a little clunky but I think it's the only way to figure out if someone didn't meet the cutoff but definitely has competed already. 

Added 3 new tests to cover all the bases (cutoff, cutoff with DNF and with incomplete)

### CODE REVIEW

File: lib/cutoff.rb [hunk 1]
```diff
@@ -14,6 +14,10 @@ def initialize(number_of_attempts: nil, attempt_result: nil, event: nil)
     self.event = event
   end
 
+  def apply(attempts)
```
Comment (gregorbg) [inline lib/cutoff.rb]: The name `apply` is not very strong. You're trying to find out whether the cutoff is "met", but I don't know whether that's actually standard WCA terminology.

In any case, the method name should end with a `?` to imply that you're returning a boolean

File: app/models/live_result.rb [hunk 2]
```diff
@@ -100,7 +100,11 @@ def should_recompute?
   end
 
   def complete?
-    live_attempts_count == round.format.expected_solve_count
+    live_attempts_count == round.format.expected_solve_count || didnt_meet_cutoff?
+  end
+
+  def didnt_meet_cutoff?
+    best != 0 && round.cutoff.present? && !round.cutoff.apply(live_attempts)
```
Comment (gregorbg) [inline app/models/live_result.rb]: Why are you using `best != 0` instead of something like `live_attempts.any?` (which should leverage the cache counter internally, feel free to confirm). My thinking is that `complete?` uses the counter, so `didnt_meet_cutoff?` can also use the counter for consistency.

**Review by gregorbg — CHANGES_REQUESTED** [review]

File: lib/cutoff.rb (hunk 1 above)
Comment (FinnIckler) [reply lib/cutoff.rb]: I introduced a meets? and exceeds? method

File: app/models/live_result.rb (hunk 2 above)
Comment (FinnIckler) [reply app/models/live_result.rb]: changed

**Review by gregorbg — APPROVED** [review]
