### PR TITLE
Check schedule and events/rounds match before confirming a competition

### LINKED ISSUE #3574: competition_wcif_spec seems to only pass if you run it in UTC time
Here's what I see when running `bin/rspec spec/models/competition_wcif_spec.rb` locally:

```
  1) Competition WCIF #to_wcif renders a valid WCIF
     Failure/Error:
       expect(competition.to_wcif).to eq(
         "formatVersion" => "1.0",
         "id" => "TestComp2014",
         "name" => "Test Comp 2014",
         "shortName" => "Test 2014",
         "persons" => [delegate.to_wcif(competition)],
         "events" => [
           {
             "id" => "333",
             "rounds" => [
     
       expected: {"events"=>[{"id"=>"333", "rounds"=>[{"advancementCondition"=>{"level"=>16, "type"=>"ranking"}, "cuto...", "id"=>3, "name"=>"Room 2 for venue 2"}], "timezone"=>"Europe/Paris"}]}, "shortName"=>"Test 2014"}
            got: {"events"=>[{"id"=>"333", "rounds"=>[{"advancementCondition"=>{"level"=>16, "type"=>"ranking"}, "cuto...", "id"=>3, "name"=>"Room 2 for venue 2"}], "timezone"=>"Europe/Paris"}]}, "shortName"=>"Test 2014"}
     
       (compared using ==)
     
       Diff:
       @@ -3,6 +3,6 @@
        "id" => "TestComp2014",
        "name" => "Test Comp 2014",
        "persons" => [{"avatar"=>{"thumbUrl"=>"http://test.host/assets/missing_avatar_thumb-f0ea801c804765a22892b57636af829edbef25260a65d90aaffbd7873bde74fc.png", "url"=>"http://test.host/assets/missing_avatar_thumb-f0ea801c804765a22892b57636af829edbef25260a65d90aaffbd7873bde74fc.png"}, "birthdate"=>"1980-01-01", "countryIso2"=>"HU", "email"=>"ianswift@macgyver.org", "gender"=>"m", "name"=>"Donnie Osinski PhD", "personalBests"=>[], "registrantId"=>nil, "registration"=>nil, "roles"=>["delegate"], "wcaId"=>"2016DYZM01", "wcaUserId"=>56}],
       -"schedule" => {"numberOfDays"=>3, "startDate"=>"2014-02-03", "venues"=>[{"id"=>1, "latitudeMicrodegrees"=>123456, "longitudeMicrodegrees"=>123456, "name"=>"Venue 1", "rooms"=>[{"activities"=>[{"activityCode"=>"other-lunch", "childActivities"=>[], "endTime"=>"2014-02-03T13:00:00Z", "id"=>1, "name"=>"Some name", "startTime"=>"2014-02-03T12:00:00Z"}, {"activityCode"=>"333fm-r1", "childActivities"=>[{"activityCode"=>"333fm-r1-g1", "childActivities"=>[], "endTime"=>"2014-02-05T10:30:00Z", "id"=>3, "name"=>"first group", "startTime"=>"2014-02-05T10:00:00Z"}, {"activityCode"=>"333fm-r1-g2", "childActivities"=>[{"activityCode"=>"333fm-r1-g2-a1", "childActivities"=>[], "endTime"=>"2014-02-05T11:00:00Z", "id"=>5, "name"=>"some nested thing", "startTime"=>"2014-02-05T10:30:00Z"}], "endTime"=>"2014-02-05T11:00:00Z", "id"=>4, "name"=>"second group", "startTime"=>"2014-02-05T10:30:00Z"}], "endTime"=>"2014-02-05T11:00:00Z", "id"=>2, "name"=>"another activity", "startTime"=>"2014-02-05T10:00:00Z"}], "color"=>"#304a96", "id"=>1, "name"=>"Room 1 for venue 1"}], "timezone"=>"Europe/Paris"}, {"id"=>2, "latitudeMicrodegrees"=>123456, "longitudeMicrodegrees"=>123456, "name"=>"Venue 2", "rooms"=>[{"activities"=>[], "color"=>"#304a96", "id"=>2, "name"=>"Room 1 for venue 2"}, {"activities"=>[], "color"=>"#304a96", "id"=>3, "name"=>"Room 2 for venue 2"}], "timezone"=>"Europe/Paris"}]},
       +"schedule" => {"numberOfDays"=>3, "startDate"=>"2014-02-03", "venues"=>[{"id"=>1, "latitudeMicrodegrees"=>123456, "longitudeMicrodegrees"=>123456, "name"=>"Venue 1", "rooms"=>[{"activities"=>[{"activityCode"=>"other-lunch", "childActivities"=>[], "endTime"=>"2014-02-03T21:00:00Z", "id"=>1, "name"=>"Some name", "startTime"=>"2014-02-03T20:00:00Z"}, {"activityCode"=>"333fm-r1", "childActivities"=>[{"activityCode"=>"333fm-r1-g1", "childActivities"=>[], "endTime"=>"2014-02-05T18:30:00Z", "id"=>3, "name"=>"first group", "startTime"=>"2014-02-05T18:00:00Z"}, {"activityCode"=>"333fm-r1-g2", "childActivities"=>[{"activityCode"=>"333fm-r1-g2-a1", "childActivities"=>[], "endTime"=>"2014-02-05T19:00:00Z", "id"=>5, "name"=>"some nested thing", "startTime"=>"2014-02-05T18:30:00Z"}], "endTime"=>"2014-02-05T19:00:00Z", "id"=>4, "name"=>"second group", "startTime"=>"2014-02-05T18:30:00Z"}], "endTime"=>"2014-02-05T19:00:00Z", "id"=>2, "name"=>"another activity", "startTime"=>"2014-02-05T18:00:00Z"}], "color"=>"#304a96", "id"=>1, "name"=>"Room 1 for venue 1"}], "timezone"=>"Europe/Paris"}, {"id"=>2, "latitudeMicrodegrees"=>123456, "longitudeMicrodegrees"=>123456, "name"=>"Venue 2", "rooms"=>[{"activities"=>[], "color"=>"#304a96", "id"=>2, "name"=>"Room 1 for venue 2"}, {"activities"=>[], "color"=>"#304a96", "id"=>3, "name"=>"Room 2 for venue 2"}], "timezone"=>"Europe/Paris"}]},
        "shortName" => "Test 2014",
       
     # ./spec/models/competition_wcif_spec.rb:36:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 13.12 seconds (files took 0.48921 seconds to load)
28 examples, 1 failure

Failed examples:

rspec ./spec/models/competition_wcif_spec.rb:35 # Competition WCIF #to_wcif renders a valid WCIF

```

It's hard to see, but the diff above is specifically in timestamps, so this feels like a timezone bug.

### PR DESCRIPTION
**Pull request by viroulep**
Fixes #3574.
:warning: This will effectively prevent organizers/Delegates from confirming a competition before they have created a valid schedule in the "Manage Schedule" page.
It should not be merged before #3018 is merged, and we should wait for when the Board is ready to enforce this.

The validation is triggered only when `isConfirmed` changes, for two reasons:
  - it's fine if old competitions do not have a schedule on the WCA website
  - for announced competitions, organizers/Delegates may add/remove rounds before the start of the competition. As we don't have a unified events+schedule editor, running the validation would fail when they add/remove a round before adjusting the schedule. Note that the "warning" alert would still be displayed in this case, to remind the organizers/Delegates that something needs to be done about it.

### CODE REVIEW

**Comment by cubewhiz** [comment]
Are there any logistical challenges with implementing this? How are tentative events handled?

**Comment by viroulep** [comment]
Tentative events are not supported currently, which seems to be the main issue as a few Delegates would like to have them.

**Comment by UnsolvedCypher** [comment]
It seems that the schedule has been in regular use for some time now, is this ready to be merged?

**Comment by cubewhiz** [comment]
I think we are waiting for WRT to confirm that they are ready for this.

**Comment by SAuroux** [comment]
Uhm, no, I don't think so. Unless I am missing something this PR is unrelated to #3127 .

**Comment by viroulep** [comment]
I didn't have any review from the WST though :(
@jfly, @jonatanklosko: would you have time to review somehow?

**Comment by cubewhiz** [comment]
Sorry @SAuroux someone mentioned this PR in the email thread and I misinterpreted one of the responses to be related to this PR instead of the original.

**Comment by jonatanklosko** [comment]
Actually, I've just realized that it would also make sense to require at least one round for each declared event. Does it sound right?

File: WcaOnRails/app/models/competition.rb [hunk 1]
```diff
@@ -197,6 +197,41 @@ class Competition < ApplicationRecord
     end
   end
 
+  # Only validate on update: nobody can confirm competition on creation.
+  # The only exception to this is within tests, in which case we actually don't want to run this validation.
+  validate :schedule_must_match_rounds, if: :confirmed_at_changed?, on: :update
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: The schedule can change after a competition gets confirmed, why would we validate it only when `confirmed_at` changes?

Comment (viroulep) [reply WcaOnRails/app/models/competition.rb]: Hum weird that I didn't include a comment about this.
Events and schedule are only editable separately, if we validate `schedule_must_match_rounds` always we'll have two issues:
  - old competitions will be invalid
  - but most importantly, changing the number of rounds for announced competition won't be possible: adding rounds through the events page won't be possible because the schedule won't contain the round just added.

Until we have a unified events/schedule page, I don't think we can validate this every time.

Maybe you have a working idea to deal with that?

Comment (jonatanklosko) [reply WcaOnRails/app/models/competition.rb]: Ah thanks, that makes sense, it definitely deserves a comment =)
As you said, probably no easy way of handling this without a single page for events and schedule, we can think it through later on.

File: WcaOnRails/app/models/schedule_activity.rb [hunk 2]
```diff
@@ -74,6 +74,13 @@ def localized_name(rounds_by_wcif_id = {})
     end
   end
 
+  # Get this activity's activity_code and all of its nested activities
+  # NOTE: as is, the WCA schedule editor doesn't support nested activities, but this
+  # doesn't prevent anyone from submitting a WCIF with 333fm-a1 nested in 333fm (for instance).
```
[the remark this answers is not in the document]
Comment (viroulep) [reply WcaOnRails/app/models/schedule_activity.rb]: We create the individual attempt activities, but they are not nested under one more generic "333fm" or "333fm-r1" activity, so I believe the comment is accurate :)

[the remark this answers is not in the document]
Comment (jonatanklosko) [reply WcaOnRails/app/models/schedule_activity.rb]: Ah, alright then ^^

**Comment by viroulep** [comment]
Just added the test for at least one round per event!

File: WcaOnRails/app/models/competition.rb [hunk 3]
```diff
@@ -193,13 +193,53 @@ class Competition < ApplicationRecord
...
+  def schedule_must_match_rounds
+    unless has_any_round_per_event? && schedule_includes_rounds?
+      errors.add(:competition_events, I18n.t('competitions.errors.schedule_must_match_rounds'))
+    end
+  end
+
+  def has_any_round_per_event?
+    competition_events.map { |ce| ce.rounds.any? }.reduce(&:&)
```
Comment (jonatanklosko) [inline WcaOnRails/app/models/competition.rb]: Haha `&:&` looks cool, but what about `competition_events.map(&:rounds).none?(&:empty?)` :D

Comment (viroulep) [reply WcaOnRails/app/models/competition.rb]: Ah right, I didn't find `none?`, it's slightly more readable!

**Comment by jonatanklosko** [comment]
Great, I believe it's ready to go! :ship: :shipit:
